// app/layout.tsx
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import SessionProviderWrapper from '../components/SessionProviderWrapper';
import Header from '../components/Header.client';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProviderWrapper session={session}>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
